### ISSUE TITLE
Add Fluffy

### ISSUE THREAD

**Issue by fourminute** [noahc3/sdsetup-switch#4]
Add Fluffy under "Windows Tools" and/or "Linux Tools".
Fluffy is a feature-rich TinFoil GUI.
https://github.com/fourminute/Fluffy

![screenshot](https://user-images.githubusercontent.com/38321299/51320638-5ab5a580-1a15-11e9-9ccb-babd831e2d55.png)

**Comment by noahc3** [comment]
Sorry for the late response, didn't notice since it wasn't on the main repo. I'll get this added ASAP!

Side note, once the application gets GoldLeaf support, would you be alright if I added it to an NSP installation guide for guide.sdsetup.com? I'm currently refactoring and redesigning the guide to include guides for common procedures, and I think people would appreciate a GUI based installer.

**Comment by fourminute** [comment]
Absolutely! I've finished working on network install as of today, so I can get to crunching in some Goldleaf time. It may take a while though, mainly due to the buggy nature of Goldleaf. But there's hope.

**Comment by noahc3** [comment]
Fluffy is now added
